server:
  address: 127.0.0.1
  port: 5000

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:BotDB.sqlite3
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  bot:
    plugin-list:
      - com.mikuac.bot.plugins.filter.TcBotFilter
      - com.mikuac.bot.plugins.aop.EventLog
      - com.mikuac.bot.plugins.aop.Maintenance
      - com.mikuac.bot.plugins.aop.SendHelp
      - com.mikuac.bot.plugins.aop.Hitokoto
      - com.mikuac.bot.plugins.aop.GroupJoinAndQuit
      - com.mikuac.bot.plugins.aop.RainbowSixStats
      - com.mikuac.bot.plugins.aop.SeTu
      - com.mikuac.bot.plugins.aop.SendAllGroup
      - com.mikuac.bot.plugins.aop.PluginSwitch
      - com.mikuac.bot.plugins.aop.WhatAnime
      - com.mikuac.bot.plugins.aop.SauceNao
      - com.mikuac.bot.plugins.aop.GetSysInfo
      - com.mikuac.bot.plugins.aop.BvToAv
      - com.mikuac.bot.plugins.Repeat
      - com.mikuac.bot.plugins.GroupAtMe
      - com.mikuac.bot.plugins.AntiBiliApp
      - com.mikuac.bot.plugins.GroupMsgCount
      - com.mikuac.bot.plugins.aop.BlockChain
      - com.mikuac.bot.plugins.aop.PhoenixWright


yuri:
  bot:
    botName: "悠里"
    adminId: 123456
    selfId: 123456
  telegram:
    proxyHost: "127.0.0.1"
    proxyPort: 1080
    botName: "@bot"
    botToken: "key_value"
  plugins:
    prefix:
      prefix: "."
    maintenance:
      isMaintenance: false
      maintenanceMsg: "yuri维护中,请稍后再试~"
    repeat:
      randomCountSize: 5
    hitokoto:
      cdTime: 10
    setu:
      apiKey: "key_value"
      cdTime: 120
      delTime: 30
      maxGet: 15
    sauceNao:
      apiKey: "key_value"
    banUtils:
      limitTime: 30
      limitCount: 5